export type FeedItem = {
  id: number;
  title: string;
  username: string;
  image: string;
  width: number;
  height: number;
  source: string;
  layout: "standard" | "tall" | "wide";
  category: "Women" | "Men" | "New" | "Trending";
};

export const feedItems: FeedItem[] = [
  {
    id: 1,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest1.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 2,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest2.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 3,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest3.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 4,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest4.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 5,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest5.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 6,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest6.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 7,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest7.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 8,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest8.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 9,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest9.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 10,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest10.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 11,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest11.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 12,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest12.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 13,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest13.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 14,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest14.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 15,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest15.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 16,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest16.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 17,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest17.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 18,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest18.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 19,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest19.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 20,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest20.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 21,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest21.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 22,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest22.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
  {
    id: 23,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest23.jpg",
    width: 1200,
    height: 820,
    source: "Pinterest",
    layout: "wide",
    category: "Women",
  },
  {
    id: 24,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest24.jpg",
    width: 800,
    height: 1200,
    source: "Pinterest",
    layout: "tall",
    category: "Women",
  },
  {
    id: 25,
    title: "Pinterest pick",
    username: "@pinterest",
    image: "/pinterest25.jpg",
    width: 800,
    height: 1000,
    source: "Pinterest",
    layout: "standard",
    category: "Women",
  },
];
